# Generated by Django 4.1 on 2022-08-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='descriptionNew',
            field=models.TextField(blank=True, max_length=360, null=True),
        ),
    ]
